# This file contains all available configuration options
# with their default values (in comments).
#
# This file is not a configuration example,
# it contains the exhaustive configuration with explanations of the options.

# Options for analysis running.
run:
  # Include test files or not.
  # Default: true
  tests: true

  # Allow multiple golangci-lint instances running, but serialize them around a lock.
  # If false, golangci-lint exits with an error if it fails to acquire file lock on start.
  # Default: false
  allow-serial-runners: true

linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
#    - copyloopvar # Unknown
    - cyclop
#    - deadcode # Deprecated
    - decorder
#    - depguard # TODO: Configure later
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
#    - exhaustivestruct # Deprecated
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits # Use builder instead of init()
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
#    - golint # Deprecated
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
#    - ifshort # Deprecated
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
#    - interfacer # Deprecated
#    - intrange # Unknown
    - ireturn
    - lll # Not shown on IntelliJ
    - loggercheck
    - maintidx
    - makezero
#    - maligned # Deprecated
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
#    - nlreturn # Not for me
    - noctx
    - nolintlint
    - nonamedreturns
#    - nosnakecase # Deprecated
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive # Not shown on IntelliJ
    - rowserrcheck
#    - scopelint # Deprecated
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
#    - structcheck # Deprecated
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
#    - varcheck # Deprecated
    - varnamelen # Not shown on IntelliJ
    - wastedassign
    - whitespace
    - wrapcheck
#    - wsl # Not for me
    - zerologlint

linters-settings:
  lll:
    line-length: 140
  goconst:
    ignore-strings: "```"

#  # Enable only fast linters from enabled linters set (first run won't be fast)
#  # Default: false
#  fast: true
